### ISSUE TITLE
setup project

### ISSUE THREAD

**Issue by naxmefy** [CodeFrogHub/php-roma-website#1]
- [x] init project
- [x] setup composer
- [x] setup slim application
- [x] add php-roma dependency
- [x] only the homepage (root "/") is needed - and is callable
- [x] frontend is showing a form to convert numbers to roman and the other way...
- [ ] try to write an integration test...
- [ ] setup travis ci
- [ ] setup coverage

**Comment by SBahrmann** [comment]
will be fixed later or never
